version: '3'

services:
  php:
    build: ./.docker/app
    container_name: php
    volumes:
      - ./backend:/app
    networks:
      - default-network
  backend:
    image: nginx:alpine
    container_name: backend
    ports:
      - 8000:80
    volumes:
      - ./backend:/app
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - default-network
  frontend:
    image: nginx:alpine
    container_name: frontend
    ports:
      - 3000:80
    volumes:
      - ./frontend/dist:/app
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - default-network
  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    tty: true
    volumes:
      - "./db-data:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - default-network
networks:
  default-network:
    driver: bridge